apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ardintel-ai-tls
spec:
  secretName: ardintel-ai
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ardintel.ai
  dnsNames:
    - ardintel.ai
    - www.ardintel.ai
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ardintel.ai
          - www.ardintel.ai
